version: "3.3"

services:
    hits_psql:
        container_name: hits_psql
        image: postgres
        restart: always
        ports:
            - ${APP_DB_PORT:-5432}:5432
        volumes:
            - hitsPsqlVolume:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: ${APP_DB_NAME:-hits}
            POSTGRES_USER: ${APP_DB_USER:-admin}
            POSTGRES_PASSWORD: ${APP_DB_PASS:-secret}
        networks:
            - hitNet

    hits_django:
        container_name: hits_django
        build: .
        volumes:
            - ./docker/hits/static:/code/static
            - .:/code
        depends_on:
            - hits_psql
        env_file:
            - .env
        networks:
            - hitNet

    hits_nginx:
        container_name: hits_nginx
        image: nginx:alpine
        volumes:
            - ./docker/nginx/sites:/etc/nginx/conf.d
            - ./docker/hits/static:/code/static
        ports:
            - ${APP_PORT:-80}:80
        depends_on:
            - hits_django
        networks:
            - hitNet

    hits_redis:
        container_name: hits_redis
        image: redis:6
        restart: always
        networks:
            - hitNet

networks:
    hitNet:
        driver: "bridge"

volumes:
    hitsPsqlVolume:
