# Generated by Django 3.1.6 on 2021-02-05 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hits', '0002_auto_20210203_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hit',
            name='user',
        ),
        migrations.AddField(
            model_name='hit',
            name='hitman',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='hit_assigned', to='users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hit',
            name='manager',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='hit_created', to='users.user'),
            preserve_default=False,
        ),
    ]
